// USER
export const LOGOUT = 'LOGOUT';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REGISTRATION_PENDING = 'REGISTRATION_PENDING'
export const REGISTERATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTERATION_ERROR = 'REGISTRATION_ERROR';

// MODALS
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

// EVENTS
export const VIEW_EVENT = 'VIEW_EVENT';
export const CREATE_EVENT = 'CREATE_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const EDIT_EVENT = 'EDIT_EVENT';

export const FETCH_ALL_EVENTS = 'FETCH_ALL_EVENTS';