// USER
export const LOGOUT = 'LOGOUT';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CLEAR_LOGIN_REG = 'CLEAR_LOGIN_REG';
export const REGISTRATION_PENDING = 'REGISTRATION_PENDING'
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';

// ENTRANT
export const FETCH_ATTENDING_EVENTS = 'FETCH_ATTENDING_EVENTS';

// MODALS
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

// EVENTS
export const VIEW_EVENT = 'VIEW_EVENT';
export const VIEW_ATTENDEES = 'VIEW_ATTNDEES';
export const FETCH_HOST = 'FETCH_HOST';
export const CREATE_EVENT = 'CREATE_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const EDIT_EVENT = 'EDIT_EVENT';
export const EVENT_ERROR = 'EVENT_ERROR';

export const FETCH_ALL_EVENTS = 'FETCH_ALL_EVENTS';